language: cpp
dist: focal
compiler: gcc

services:
  - xvfb
    
install:
- sudo apt-get install libsfml-dev
- sudo apt-get install qt5-default
- sudo apt-get install lcov

script:
- cd 3rdParty/Box2D
- qmake
- make
- cd ../../src/RealBasket
- qmake
- make
- cd ../../tests
- qmake
- make
- cd ../bin
- ./tests
after_success:
- bash <(curl -s https://codecov.io/bash)
