language: cpp
dist: focal
compiler: gcc

install:
- sudo apt-get install libsfml-dev
- sudo apt-get install qt5-default

script:
- cd src/RealBasket
- qmake
- make
- cd ../../tests
- qmake
- make
- cd ../scripts
- ./coverage.sh
after_success:
- bash <(curl -s https://codecov.io/bash)
